# Traffic Monitoring
{{ $trafficMonitoringNamespace := "traffic-monitoring" }}

# OpenSearch
{{ $opensearchNamespace := "opensearch" }}

# Registry credentials
{{ $registry := requiredEnv "REGISTRY" }}
{{ $registryUsername := requiredEnv "REGISTRY_USER" }}
{{ $registryPassword := requiredEnv "REGISTRY_PASSWORD" }}

repositories:

  - name: opensearch
    url: https://opensearch-project.github.io/helm-charts/

helmDefaults:
  wait: false
  waitForJobs: false

releases:

  ##############################################################################
  # Traffic Monitoring app
  ##############################################################################


  - name: "traffic-monitoring"
    namespace: {{ $trafficMonitoringNamespace | quote }}
    createNamespace: true
    # TODO: Fetch chart from the artifact registry. We'll be able to do that when we can tag chart OCI images with pipeline IDs. See https://jira.aes.alcatel.fr:8443/browse/DEVOPSSP-499
    chart: ../../helm/charts
    values:
      - image:
          pullPolicy: IfNotPresent
          registry: {{ $registry | quote }}
          pullSecret:
            username: {{ $registryUsername | quote }}
            password: {{ $registryPassword | quote }}
        detector:
          imageTag: "0.0.1"
        stateInit:
          imageTag: "0.0.1"
        opensearchDashboards:
          host: {{ print "opensearch-dashboards." $opensearchNamespace ".svc.cluster.local" | quote }}
          port: 5601
          resourcesPath: "/opt/resources/"
        opensearch:
          host: {{ print "opensearch." $opensearchNamespace ".svc.cluster.local" | quote }}
          port: 9200
        debug: false
        localDeployment: true # Inhibits CPU & memory requests & limits


  ##############################################################################
  # OpenSearch
  ##############################################################################

  - name: "opensearch"
    namespace: {{ $opensearchNamespace }}
    chart: opensearch/opensearch
    version: v3.0.0
    values:
      - singleNode: true
        replicas: 1
        extraEnvs:
          - name: DISABLE_SECURITY_PLUGIN
            value: "true"

  - name: "opensearch-dashboards"
    namespace: {{ $opensearchNamespace }}
    chart: opensearch/opensearch-dashboards
    values:
      - opensearchHosts:
        - "http://opensearch-cluster-master:9200"
      - extraEnvs:
          - name: DISABLE_SECURITY_DASHBOARDS_PLUGIN
            value: "true"