apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-detector
  labels:
    app: traffic-monitoring
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: traffic-monitoring
  template:
    metadata:
      labels:
        app: traffic-monitoring
    spec:
      containers:
        - name: main
          image: {{ printf "%s/%s:%s" (required "Registry is required" .Values.image.registry) "detector" (.Values.detector.imageTag ) | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
      imagePullSecrets:
        - name: secret-registry-credentials