{{- if .Values.image.pullSecret -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: secret-registry-credentials
data:
  .dockerconfigjson: {{ include "detector.imagePullDockerConfigJson" . }}
{{- end -}}
