# name: Github Actions Demo
# run-name: ${{ github.actor }} is testing out Github Actions
# on: [push]
# jobs:
#   Explore-Github-Actions:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "The job was automatically triggered by a ${{ github.event_name }} event"

#       - name: Check out repository code
#         uses: actions/checkout@v4
#       - run: echo "The ${{ github.repository }} repository has been cloned to the runner"

#       - name: List files of repository
#         run: |
#           ls ${{ github.workspace }}

name: Build and Publish to GHCR

on:
  push:
    # branches:
    #   - main  # Only trigger on merge into main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: danim55
          password: ${{ secrets.ARTIFACTORY_TOKEN }}

      - name: Build and Push Docker image
        run: |
          cd detector
          docker build --build-arg ENVIRONMENT=PROD -t ghcr.io/danim55/traffic-monitoring/detector:0.0.1 .
          docker push ghcr.io/danim55/traffic-monitoring/detector:0.0.1
