name: Auto Approve PR

on:
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request Number'
        required: true
        type: string

permissions:
  pull-requests: write
  contents: read

jobs:
  auto-approve:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, 'APPROVED') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.APPROVER_TOKEN }}

      - name: Approve Pull Request
        env:
          GH_TOKEN: ${{ secrets.APPROVER_TOKEN }}
          PR_NUMBER: ${{ github.event.issue.number || inputs.pr_number }}
          REPO: ${{ github.repository }}
        run: |
          gh pr review $PR_NUMBER --approve --repo $REPO
