name: Auto Approve Pull Request

on:
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request Number (for manual trigger)'
        required: true
        type: string

permissions:
  pull-requests: write
  contents: read

jobs:
  auto-approve:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(github.event.comment.body, '-APPROVED-')) }}
    runs-on: ubuntu-latest

    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Checkout repository
        uses: action/checkout@v4
        with:
          token: ${{ secrets.APPROVER_TOKEN }}

      - name: Approve Pull Request
        env:
          GH_TOKEN: ${{ secrets.APPROVER_TOKEN }}
          PR_NUMBER: ${{ github.event.issue.number || inputs.pr_number }}
          REPO: ${{ github.repository }}
        run: |
          echo "Approving PR #${PR_NUMBER}" in ${REPO}
          gh auth setup-git
          gh pr review $PR_NUMBER --approve --repo $REPO
            